# Generated by Django 5.1 on 2024-09-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_remove_čojz_otázka_choice_delete_otázka_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
